
server:
  port: 8770
spring:
  application:
    name: contentMS
  data:
    mongodb:
      uri: mongodb://localhost:27017/post_db
  cloud:
    consul:
      host: localhost
      discovery:
        hostname: localhost
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
          


storage:
  path: C:\\Users\\vishal.singh53\\frontendGit\\group5-frontend\\src\\assets\\uploadedImages\\ 