
server:
  port: 8780
spring:
  application:
    name: recruitmentMS
  data:
    mongodb:
      uri: mongodb://localhost:27017/job_db
  cloud:
    consul:
      host: localhost
      discovery:
        hostname: localhost